paths:
  /api/products:
    get:
      summary: Obtiene todos los productos de la base de datos
      tags:
        - Products
      responses: 
        '200':
          description: Los productos fueron obtenidos satisfactoriamente de la base de datos
        '500':
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo en la conexion con la base de datos
        '400':
          description: No se pudieron obtener todos los productos solicitados
    post:
      summary: Agrega un producto a la base de datos
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/product'  
      responses:
        '200':
          description: Producto agregado satisfactoriamente a la base de datos
        '500':
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo en la conexion con la base de datos
        '400':
          description: No se pudo agregar el producto a la base de datos            
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: Identificador unico del producto que desea obtener
          required: true      
      responses: 
          '200':
            description: Producto obtenido satisfactoriamente de la base de datos
            content:
              application/json:
                schemas:
                  $ref: '#/components/schemas/Product'  
          '500':
            description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo en la conexion con la base de datos
          '400':
            description: No se pudieron obtener el producto solicitado
    put:
      summary: Modificar un producto pasando el ID y el campo a modificar
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: Identificador unico del producto que desea modificar
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/product'
      responses: 
        '200':
          description: Producto modificado satisfactoriamente de la base de datos
          content:
            application/json:
              schemas:
                $ref: '#/components/schemas/Product'  
        '500':
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo en la conexion con la base de datos
        '400':
          description: No se pudo modificar el producto solicitado, usualmente porque el usuario no inicio sesion o no tiene el permiso para hacer la operacion
    delete:
      summary: Elimina un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          description: Identificador unico del producto que desea eliminar
          required: true      
      responses: 
          '200':
            description: Producto eliminado satisfactoriamente de la base de datos
            content:
              application/json:
                schemas:
                  $ref: '#/components/schemas/Product'  
          '500':
            description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo en la conexion con la base de datos
          '400':
            description: No se pudo eliminar el producto solicitado, usualmente porque el usuario no inicio sesion o no tiene el permiso para hacer la operacion               
               
components:
  schemas:
    Product:
      type: object
      properties:
        pid:
          type: objectId
          description: ID autogenerado por mongo
        title:
          type: string
          description: Titulo del producto
        description:
          type: string
          description: Descripcion del producto
        code:
          type: string
          description: Codigo autogenerado unico por cada producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Status del producto
        stock:
          type: number
          description: Stock disponible del producto
        category:
          type: string
          description: Categoria del producto
        image:
          type: string
          description: Imagen del producto
        size:
          type: string
          description: Talle del producto
        owner:
          type: string
          description: Dueño del producto generado a traves de un req.session de acuerdo al usuario que inicio sesion            
      example:
        id: 64655495f363087e7d24e036
        title: Sweater coral
        description: Sweater coral
        code: T8OHHx8Xgz
        price: 800
        status: true
        stock: 2
        category: usado
        image: ../Assets/sweater-coral.jpg
        size: Único
        owner: roo.fernandez88@gmail.com
  requestBodies:
    product:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        status:
          type: boolean
        stock:
          type: number
        category:
          type: string
        image:
          type: string
        size:
          type: string                   
